### ISSUE TITLE
0.0.4 Release

### ISSUE THREAD

**Issue by SquarerFive** [SquarerFive/bf3-bots#14]
- [x] Document Installation Process: #12 
- [x] Bots to emit and provide when below a certain health or ammo threshold. #3 
- ~~Query all vehicles from the map, bot will pick the closest one to enter automatically. #6~~ [moved to 0.0.5]
- [x] Ensure this is fixed, and document how it was fixed. #1
- [x] Improve pathing so bots don't get stuck on large objects #15 
- [x] Fix random firing, bots should only be firing at enemies (or melee attacking an obstacle).
